---
title: "R Notebook"
output: html_notebook
---
```{r}
#set working directory and bring in the Excel Sheet
#setwd("~/University/University 2020-2021/thesis/MicrobiomeThesis")
library(readxl)
library(tidyverse)
library(ggmosaic)
# set plotting theme
theme_set(theme_bw())
#~/University/University 2020-2021/thesis/MicrobiomeThesis/
# read in spreadsheets
ResultsMicrobiome <- read_excel("micro.xlsx")
```

```{r}
# replace NAs with no
ResultsMicrobiome$NestedCore[is.na(ResultsMicrobiome$NestedCore)] <- "no"
# combine cores
ResultsMicrobiome$CombinedCore <- interaction(ResultsMicrobiome$NestedCore,
                                              ResultsMicrobiome$CommonCore,
                                              ResultsMicrobiome$TemporalCore) %>%
  str_replace_all(c("ecological.no.no" = "Ecological\n(with or without Common)",
                  "functional.no.no" = "Functional\n(with or without Common)",
                  "host-adapted.no.no" = "Host-adapted\n(with or without Common)",
                  "ecological.yes.no" = "Ecological\n(with or without Common)",
                  "functional.yes.no" = "Functional\n(with or without Common)",
                  "host-adapted.yes.no" = "Host-adapted\n(with or without Common)",
                  "no.yes.no" = "Common Only", "no.no.yes" = "Temporal\n(All Combinations)",
                  "ecological.yes.yes" = "Temporal\n(All Combinations)",
                  "functional.yes.yes" = "Temporal\n(All Combinations)",
                  "no.no.no" = "None", "no.yes.yes" = "Temporal\n(All Combinations)",
                  "host-adapted.yes.yes" = "Temporal\n(All Combinations)"))
# fish are vertebrate, so merging those groups
ResultsMicrobiome$HostType <- ResultsMicrobiome$HostType %>% str_replace_all(c("fish" = "vertebrate"))
# make a list with types of core to loop over
coreTypes <- c("Common", "Temporal", "Host-adapted", "Functional", "Ecological")
```

### Primary Analyses, Chi Square Tests
Types of core: Common, temporal, ecological, functional, host-adapted
```{r}
FOS <- table(ResultsMicrobiome$CombinedCore, ResultsMicrobiome$FieldOfStudy) %>% chisq.test()
FOS
```
```{r}
HT <- table(ResultsMicrobiome$CombinedCore, ResultsMicrobiome$HostType) %>% chisq.test()
HT
```

```{r}
PNI <- table(ResultsMicrobiome$CombinedCore, ResultsMicrobiome$PositiveOrNegativeInteraction) %>% chisq.test()
PNI
```

```{r}
EHF <- table(ResultsMicrobiome$CombinedCore, ResultsMicrobiome$EffectOnHostFitness) %>%
  as.data.frame() %>% # converting to a data frame
  pivot_wider(names_from = Var2, values_from = Freq) %>% column_to_rownames("Var1") %>%
  # dropping zero 0 rows to run the chisquare test
  .[ rowSums(.)!=0, ] %>% chisq.test()
EHF
```

### Bonferroni Test

```{r}
pval <- c((FOS[["p.value"]]), 
          (HT[["p.value"]]),
          (PNI[["p.value"]]),
          (EHF[["p.value"]])) %>% unlist

#first row is unadjusted pvalues
pval

#second row is Bonferroni-Holm adjusted pvalues
p.adjust(pval, method = "holm")
```

### Visualization - Mosaic Bar Plots

```{r}
# combined core
ResultsMicrobiome$CombinedCore <- factor(ResultsMicrobiome$CombinedCore,
                                         levels = c("Common Only",
                                                    "Ecological\n(with or without Common)", 
                                                    "Functional\n(with or without Common)",
                                                    "Host-adapted\n(with or without Common)", 
                                                    "Temporal\n(All Combinations)",
                                                    "None"))
                                         
# field of study
ResultsMicrobiome$FieldOfStudy <- factor(ResultsMicrobiome$FieldOfStudy, 
                                         levels = c("Ecology", "Medical",
                                                    "Agricultural", "Industrial"))
# host types
table(ResultsMicrobiome$HostType)
ResultsMicrobiome$HostType <- factor(ResultsMicrobiome$HostType,
                                     levels = c("vertebrate", "human", "invertebrate", "plant",
                                                "food products", "soil", "sludge",  "water"))
# positive/negative
table(ResultsMicrobiome$PositiveOrNegativeInteraction)
ResultsMicrobiome$PositiveOrNegativeInteraction <- factor(ResultsMicrobiome$PositiveOrNegativeInteraction,
                                     levels = c("both", "positive", "negative"))

# host fitness
table(ResultsMicrobiome$EffectOnHostFitness)
ResultsMicrobiome$EffectOnHostFitness <- factor(ResultsMicrobiome$EffectOnHostFitness,
                                     levels = c("both", "positive", "negative"))
```

```{r}
# figure foundation
f <- ggplot(ResultsMicrobiome) +
  scale_fill_viridis_d() +
  labs(fill = "Combined Core", y = "Combined Core")
```

```{r}
# field of study x core microbiome
# un-comment pdf and dev.off to export with unsquished labels
pdf("MosaicPlots/FieldOfStudy.pdf", height = 10, width = 15)
f + geom_mosaic(aes(x = product(FieldOfStudy),
                    fill = CombinedCore)) +
  xlab("Field of Study") +
  theme(axis.title.x = element_text(size = 16, face = "bold"),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 12, face = "italic"),
        axis.text.x = element_text(size = 12, face = "italic"), legend.position = "none")

dev.off()
```


```{r}
# study system x core microbiome
pdf("MosaicPlots/StudySystem.pdf", height = 10, width = 15)
f + geom_mosaic(aes(x = product(HostType),
                    fill = CombinedCore)) +
  xlab("Study System") +
   theme(axis.title.x = element_text(size = 16, face = "bold"),
         axis.title.y = element_text(size = 16, face = "bold"),
         axis.text.y = element_text(size = 12, face = "italic"),
         axis.text.x = element_text(size = 12, face = "italic"), legend.position = "none")

dev.off()
```

```{r}
# positive or negative interaction x core microbiome
pdf("MosaicPlots/InteractionType.pdf", height = 10, width = 15)
f + geom_mosaic(aes(x = product(PositiveOrNegativeInteraction),
                    fill = CombinedCore)) +
  xlab("Interaction Type") +
   theme(axis.title.x = element_text(size = 16, face = "bold"),
         axis.title.y = element_text(size = 16, face = "bold"),
         axis.text.y = element_text(size = 12, face = "italic"),
         axis.text.x = element_text(size = 12, face = "italic"), legend.position = "none")

dev.off()
```

```{r}
# effect on host fitness x core microbiome
pdf("MosaicPlots/EffectHostFitness.pdf", height = 10, width = 15)
f + geom_mosaic(aes(x = product(EffectOnHostFitness),
                    fill = CombinedCore)) +
  xlab("Effect on Host Fitness") +
  theme(axis.title.x = element_text(size = 16, face = "bold"),
        axis.title.y = element_text(size = 16, face = "bold"),
        axis.text.y = element_text(size = 12, face = "italic"),
        axis.text.x = element_text(size = 12, face = "italic"), legend.position = "none")

dev.off()
```
